/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Untitled.glb -o Model.jsx 
*/

import React from "react";
import { useGLTF, useAnimations, useFBX } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const { isHovered = false, ...restProps } = props;
  const modelRootRef = React.useRef(null);
  const activeActionRef = React.useRef(null);
  const [isAnimationReady, setIsAnimationReady] = React.useState(false);
  const { scene } = useGLTF("/models/Untitled.glb");
  const idleFbx = useFBX("/animations/Breathing Idle.fbx");
  const greetingFbx = useFBX("/animations/Standing Greeting.fbx");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);

  const animationClips = React.useMemo(() => {
    const clips = [];

    const idleClip = idleFbx.animations?.[0]?.clone();
    if (idleClip) {
      idleClip.name = "Breathing Idle";
      clips.push(idleClip);
    }

    const greetingClip = greetingFbx.animations?.[0]?.clone();
    if (greetingClip) {
      greetingClip.name = "Standing Greeting";
      clips.push(greetingClip);
    }

    return clips;
  }, [idleFbx, greetingFbx]);

  const { actions, mixer } = useAnimations(animationClips, modelRootRef);
  const idleAction = actions?.["Breathing Idle"] || null;
  const greetingAction = actions?.["Standing Greeting"] || null;

  React.useEffect(() => {
    activeActionRef.current = null;
    setIsAnimationReady(false);
  }, [clone]);

  const switchAction = React.useCallback(
    (nextAction) => {
      if (!nextAction || activeActionRef.current === nextAction) {
        return;
      }

      if (
        activeActionRef.current &&
        typeof activeActionRef.current.fadeOut === "function"
      ) {
        activeActionRef.current.fadeOut(0.2);
      }

      if (
        typeof nextAction.reset === "function" &&
        typeof nextAction.fadeIn === "function" &&
        typeof nextAction.play === "function"
      ) {
        nextAction.reset().fadeIn(0.2).play();
        activeActionRef.current = nextAction;

        if (mixer && typeof mixer.update === "function") {
          mixer.update(0);
        }

        requestAnimationFrame(() => {
          setIsAnimationReady(true);
        });
      }
    },
    [mixer],
  );

  React.useEffect(() => {
    const availableActions = Object.values(actions || {}).filter(
      (action) => action && typeof action.play === "function",
    );

    if (!availableActions.length) {
      return;
    }

    const fallbackAction = availableActions[0];
    const nextAction = isHovered
      ? greetingAction || idleAction || fallbackAction
      : idleAction || greetingAction || fallbackAction;

    switchAction(nextAction);
  }, [actions, idleAction, greetingAction, isHovered, switchAction]);

  React.useEffect(() => {
    return () => {
      Object.values(actions || {}).forEach((action) => {
        if (action && typeof action.stop === "function") {
          action.stop();
        }
      });
    };
  }, [actions]);

  return (
    <group
      ref={modelRootRef}
      {...restProps}
      dispose={null}
      visible={isAnimationReady}
    >
      <primitive object={clone} />
    </group>
  );
}

useGLTF.preload("/models/Untitled.glb");
useFBX.preload("/animations/Breathing Idle.fbx");
useFBX.preload("/animations/Standing Greeting.fbx");
