/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/Untitled.glb -o Model.jsx 
*/

import React from "react";
import { useFrame, useGraph } from "@react-three/fiber";
import { useGLTF, useAnimations, useFBX } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";

export function Model(props) {
  const { isHovered = false, ...restProps } = props;
  const group = React.useRef();
  const activeActionRef = React.useRef(null);
  const { scene } = useGLTF("/models/Untitled.glb");
  const idleFbx = useFBX("/animations/Breathing Idle.fbx");
  const greetingFbx = useFBX("/animations/Standing Greeting.fbx");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);
  const hasExpectedRig =
    !!nodes?.mixamorigHips &&
    !!nodes?.vanguard_Mesh?.geometry &&
    !!nodes?.vanguard_Mesh?.skeleton &&
    !!nodes?.vanguard_visor?.geometry &&
    !!nodes?.vanguard_visor?.skeleton &&
    !!materials?.VanguardBodyMat &&
    !!materials?.Vanguard_VisorMat;

  const animationClips = React.useMemo(() => {
    const clips = [];

    const idleClip = idleFbx.animations?.[0]?.clone();
    if (idleClip) {
      idleClip.name = "Breathing Idle";
      clips.push(idleClip);
    }

    const greetingClip = greetingFbx.animations?.[0]?.clone();
    if (greetingClip) {
      greetingClip.name = "Standing Greeting";
      clips.push(greetingClip);
    }

    return clips;
  }, [idleFbx, greetingFbx]);

  const { actions } = useAnimations(animationClips, group);
  const idleAction = actions?.["Breathing Idle"] || null;
  const greetingAction = actions?.["Standing Greeting"] || null;

  const switchAction = React.useCallback((nextAction) => {
    if (!nextAction || activeActionRef.current === nextAction) {
      return;
    }

    if (
      activeActionRef.current &&
      typeof activeActionRef.current.fadeOut === "function"
    ) {
      activeActionRef.current.fadeOut(0.22);
    }

    if (
      typeof nextAction.reset === "function" &&
      typeof nextAction.fadeIn === "function" &&
      typeof nextAction.play === "function"
    ) {
      nextAction.reset().fadeIn(0.22).play();
      activeActionRef.current = nextAction;
    }
  }, []);

  useFrame(() => {
    const availableActions = Object.values(actions || {}).filter(
      (action) => action && typeof action.play === "function",
    );

    if (!availableActions.length) {
      return;
    }

    const fallbackAction = availableActions[0];
    const nextAction = isHovered
      ? greetingAction || idleAction || fallbackAction
      : idleAction || greetingAction || fallbackAction;

    switchAction(nextAction);
  });

  React.useEffect(() => {
    return () => {
      Object.values(actions || {}).forEach((action) => {
        if (action && typeof action.stop === "function") {
          action.stop();
        }
      });
    };
  }, [actions]);

  return (
    <group ref={group} {...restProps} dispose={null}>
      {hasExpectedRig ? (
        <group name="Scene">
          <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <primitive object={nodes.mixamorigHips} />
            <skinnedMesh
              name="vanguard_Mesh"
              geometry={nodes.vanguard_Mesh.geometry}
              material={materials.VanguardBodyMat}
              skeleton={nodes.vanguard_Mesh.skeleton}
            />
            <skinnedMesh
              name="vanguard_visor"
              geometry={nodes.vanguard_visor.geometry}
              material={materials.Vanguard_VisorMat}
              skeleton={nodes.vanguard_visor.skeleton}
            />
          </group>
        </group>
      ) : (
        <primitive object={clone} />
      )}
    </group>
  );
}

useGLTF.preload("/models/Untitled.glb");
useFBX.preload("/animations/Breathing Idle.fbx");
useFBX.preload("/animations/Standing Greeting.fbx");
