/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/name.glb -o src/components/NameModel.jsx 
*/

import React from "react";
import { useFrame } from "@react-three/fiber";
import { useGLTF } from "@react-three/drei";
import { Color } from "three";

export function NameModel(props) {
  const { mobileHoldActive = false, ...restProps } = props;
  const [hoveredLetter, setHoveredLetter] = React.useState(null);
  const [heldLetter, setHeldLetter] = React.useState(null);
  const [pulsedLetter, setPulsedLetter] = React.useState(null);
  const [isMobileView, setIsMobileView] = React.useState(false);
  const groupRef = React.useRef(null);
  const { nodes, materials } = useGLTF("/models/name.glb");
  const baseColorsRef = React.useRef(new Map());
  const hoverColorRef = React.useRef(new Color("#90EE90"));
  const pulseColorRef = React.useRef(new Color("#90EE90"));
  const letterNamesRef = React.useRef([]);

  React.useEffect(() => {
    if (!groupRef.current) {
      return;
    }

    groupRef.current.traverse((child) => {
      if (!child?.isMesh) {
        return;
      }

      const nodeName = child.name || "";
      if (!/^txt\.?\d+$/i.test(nodeName)) {
        return;
      }

      if (Array.isArray(child.material)) {
        return;
      }

      child.material = child.material.clone();
      baseColorsRef.current.set(child.uuid, child.material.color.clone());

      if (!letterNamesRef.current.includes(nodeName)) {
        letterNamesRef.current.push(nodeName);
      }
    });
  }, []);

  React.useEffect(() => {
    if (
      typeof window === "undefined" ||
      typeof window.matchMedia !== "function"
    ) {
      return;
    }

    const mediaQuery = window.matchMedia(
      "(max-width: 760px) and (pointer: coarse)",
    );
    const updateMobileState = () => {
      setIsMobileView(mediaQuery.matches);
    };

    updateMobileState();

    if (typeof mediaQuery.addEventListener === "function") {
      mediaQuery.addEventListener("change", updateMobileState);
    } else if (typeof mediaQuery.addListener === "function") {
      mediaQuery.addListener(updateMobileState);
    }

    return () => {
      if (typeof mediaQuery.removeEventListener === "function") {
        mediaQuery.removeEventListener("change", updateMobileState);
      } else if (typeof mediaQuery.removeListener === "function") {
        mediaQuery.removeListener(updateMobileState);
      }
    };
  }, []);

  React.useEffect(() => {
    const isRandomPulseMode = isMobileView && mobileHoldActive;

    if (!isRandomPulseMode) {
      setPulsedLetter(null);
      return;
    }

    const pulse = () => {
      const letterNames = letterNamesRef.current;
      if (!letterNames.length) {
        return;
      }

      const randomIndex = Math.floor(Math.random() * letterNames.length);
      setPulsedLetter(letterNames[randomIndex]);
      pulseColorRef.current.setHSL(Math.random(), 0.78, 0.62);
    };

    pulse();
    const intervalId = window.setInterval(pulse, 1000);

    return () => {
      window.clearInterval(intervalId);
    };
  }, [isMobileView, mobileHoldActive]);

  useFrame((_, delta) => {
    if (!groupRef.current) {
      return;
    }

    const isRandomPulseMode = isMobileView && mobileHoldActive;

    groupRef.current.traverse((child) => {
      if (!child?.isMesh) {
        return;
      }

      const nodeName = child.name || "";
      const isLetter = /^txt\.?\d+$/i.test(nodeName);
      if (!isLetter) {
        return;
      }

      const activeLetter = isRandomPulseMode
        ? pulsedLetter
        : heldLetter || hoveredLetter;

      const activeColor = isRandomPulseMode
        ? pulseColorRef.current
        : hoverColorRef.current;

      const activeScale = isRandomPulseMode ? 1.16 : 1.08;

      const targetScale = nodeName === activeLetter ? activeScale : 1;
      const nextScale =
        child.scale.x + (targetScale - child.scale.x) * Math.min(1, delta * 12);
      child.scale.setScalar(nextScale);

      if (Array.isArray(child.material) || !child.material?.color) {
        return;
      }

      const baseColor = baseColorsRef.current.get(child.uuid);
      if (!baseColor) {
        return;
      }

      const targetColor = nodeName === activeLetter ? activeColor : baseColor;
      child.material.color.lerp(targetColor, Math.min(1, delta * 12));
    });
  });

  return (
    <group
      ref={groupRef}
      {...restProps}
      dispose={null}
      onPointerMove={(event) => {
        const objectName = event.object?.name || "";
        setHoveredLetter(/^txt\.?\d+$/i.test(objectName) ? objectName : null);
      }}
      onPointerDown={(event) => {
        const objectName = event.object?.name || "";
        if (/^txt\.?\d+$/i.test(objectName)) {
          setHeldLetter(objectName);
          setHoveredLetter(objectName);
        }
      }}
      onPointerUp={() => setHeldLetter(null)}
      onPointerCancel={() => setHeldLetter(null)}
      onPointerOut={() => {
        setHoveredLetter(null);
        setHeldLetter(null);
      }}
    >
      <mesh
        name="txt.13"
        geometry={nodes.txt13.geometry}
        material={materials["Material.001"]}
      />
      <mesh
        name="txt.12"
        geometry={nodes.txt12.geometry}
        material={nodes.txt12.material}
      />
      <mesh
        name="txt.11"
        geometry={nodes.txt11.geometry}
        material={nodes.txt11.material}
      />
      <mesh
        name="txt.10"
        geometry={nodes.txt10.geometry}
        material={nodes.txt10.material}
      />
      <mesh
        name="txt.9"
        geometry={nodes.txt9.geometry}
        material={nodes.txt9.material}
      />
      <mesh
        name="txt.8"
        geometry={nodes.txt8.geometry}
        material={nodes.txt8.material}
      />
      <mesh
        name="txt.7"
        geometry={nodes.txt7.geometry}
        material={nodes.txt7.material}
      />
      <mesh
        name="txt.6"
        geometry={nodes.txt6.geometry}
        material={nodes.txt6.material}
      />
      <mesh
        name="txt.5"
        geometry={nodes.txt5.geometry}
        material={nodes.txt5.material}
      />
      <mesh
        name="txt.4"
        geometry={nodes.txt4.geometry}
        material={nodes.txt4.material}
      />
      <mesh
        name="txt.3"
        geometry={nodes.txt3.geometry}
        material={nodes.txt3.material}
      />
      <mesh
        name="txt.2"
        geometry={nodes.txt2.geometry}
        material={nodes.txt2.material}
      />
      <mesh
        name="txt.1"
        geometry={nodes.txt1.geometry}
        material={nodes.txt1.material}
      />
    </group>
  );
}

useGLTF.preload("/models/name.glb");
